version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: app
    networks:
      - nodenet
  nginx:
    build: 
      context: .
      dockerfile: dockerfile.nginx
    image: luizeduu/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - db:/var/lib/mysql
    networks:
      - nodenet
    

networks:
  nodenet:
    driver: bridge

volumes:
  db:
    