version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: dockerfile.node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- npm start
    depends_on:
      - db
    networks:
      - nodenet
    volumes:
      - .:/usr/app

  nginx:
    build: 
      context: .
      dockerfile: dockerfile.nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - db:/var/lib/mysql
    networks:
      - nodenet
    

networks:
  nodenet:
    driver: bridge

volumes:
  db:
    