FROM node:20

RUN  apt update -y && \
     apt install bash -y && \
     apt install wget netcat-openbsd -y && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for


WORKDIR /home/node/app

COPY package*.json .


EXPOSE 3000
