FROM node:20

RUN  apt update -y && \
     apt install bash -y && \
     apt install wget netcat-openbsd -y && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for


WORKDIR /home/node/app

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 3000

ENTRYPOINT [ "wait-for", "db:3306", "-t 40", "--", "npm", "run", "start" ]
